### ISSUE TITLE
raven-controller-manager pod run error: can't start webhook-controller

### ISSUE THREAD

**Issue by showeriszero** [openyurtio/raven-controller-manager#34]
raven-controller-manager pod run error，please check follow logs.

zxvuz0.fyamhljzy47j7d93   9h          2023-02-03T12:24:55Z   authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token
root@master:~/install/openyurt/raven-controller-manager/config/setup# kubectl logs raven-controller-manager-58967476b-z5znj -n kube-system
I0203 02:56:49.246008       1 logr.go:249] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8080"
I0203 02:56:49.246675       1 logr.go:249] controller-runtime/builder "msg"="Registering a mutating webhook"  "GVK"={"Group":"raven.openyurt.io","Version":"v1alpha1","Kind":"Gateway"} "path"="/mutate-raven-openyurt-io-v1alpha1-gateway"
I0203 02:56:49.246862       1 server.go:146] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-raven-openyurt-io-v1alpha1-gateway"
I0203 02:56:49.247475       1 logr.go:249] controller-runtime/builder "msg"="Registering a validating webhook"  "GVK"={"Group":"raven.openyurt.io","Version":"v1alpha1","Kind":"Gateway"} "path"="/validate-raven-openyurt-io-v1alpha1-gateway"
I0203 02:56:49.247584       1 server.go:146] controller-runtime/webhook "msg"="Registering webhook" "path"="/validate-raven-openyurt-io-v1alpha1-gateway"
I0203 02:56:49.248742       1 webhook_controller.go:156] Starting webhook-controller
I0203 02:56:49.248797       1 shared_informer.go:240] Waiting for caches to sync for webhook-controller
I0203 02:56:49.346020       1 webhook_controller.go:119] MutatingWebhookConfiguration raven-mutating-webhook-configuration added
I0203 02:56:49.346042       1 webhook_controller.go:136] ValidatingWebhookConfiguration raven-validating-webhook-configuration added
I0203 02:56:49.748060       1 webhook_controller.go:102] Secret kube-system/raven-webhook-certs added
I0203 02:56:49.843381       1 shared_informer.go:247] Caches are synced for webhook-controller
I0203 02:56:49.843423       1 webhook_controller.go:168] Started webhook-controller
I0203 02:56:49.843491       1 webhook_controller.go:193] Starting to sync webhook certs and configurations
I0203 02:56:49.843515       1 webhook_controller.go:213] Use Secret Cert Writer
E0203 02:56:49.847261       1 certwriter.go:109] valid cert error is null
I0203 02:56:49.847290       1 certwriter.go:69] cert is invalid or expiring, regenerating a new one
E0203 02:56:54.249861       1 logr.go:265] setup "msg"="problem initializing webhook" "error"="failed to start webhook controller for waiting more than 5s"

can you help me manual fix this problem, thx.

**Comment by njucjc** [comment]
try to run 'kubectl get secret raven-webhook-certs -n kube-system' to check this secret is exists or not

**Comment by showeriszero** [comment]
> try to run 'kubectl get secret raven-webhook-certs -n kube-system' to check this secret is exists or not

kubectl get secret raven-webhook-certs -n kube-system
NAME                  TYPE     DATA   AGE
raven-webhook-certs   Opaque   0      89m

is this secret is exists? thx

**Comment by showeriszero** [comment]
describe it, it's like empty.


kubectl describe secret -n kube-system raven-webhook-certs
<img width="355" alt="image" src="https://user-images.githubusercontent.com/32185980/216508093-8d811a5f-a5a5-46bd-8ce0-23f919fac484.png">

**Comment by njucjc** [comment]
> describe it, it's like empty.
> 
> kubectl describe secret -n kube-system raven-webhook-certs <img alt="image" width="355" src="https://user-images.githubusercontent.com/32185980/216508093-8d811a5f-a5a5-46bd-8ce0-23f919fac484.png">

it seems webhook certs is not generate cc @DrmagicE

**Comment by njucjc** [comment]
> describe it, it's like empty.
> 
> kubectl describe secret -n kube-system raven-webhook-certs <img alt="image" width="355" src="https://user-images.githubusercontent.com/32185980/216508093-8d811a5f-a5a5-46bd-8ce0-23f919fac484.png">

you can add some debug log in this function

![image](https://user-images.githubusercontent.com/15940738/216521088-549add14-82d9-41c7-bb47-1e6bb3d3a821.png)

**Comment by showeriszero** [comment]
@njucjc sorry, i use follow way to create raven-controller-manager deployment.
git clone https://github.com/openyurtio/raven-controller-manager.git
cd raven-controller-manager
git checkout v0.3.0
make generate-deploy-yaml
kubectl apply -f _output/yamls/raven-controller-manager.yaml

can't build a debug version and use it.

**Comment by showeriszero** [comment]
after i deploy a edge node, raven-controller-manager  well done， running successed.
