### ISSUE TITLE
helm chart service can't select endpoints

### ISSUE THREAD

**Issue by arctan90** [openyurtio/raven-controller-manager#38]
After helm install the chart, I find that Gateway can not be applied, because no webhook is found. So I checked the ep```raven-webhook-service```  came to no ENDPOINTS in it.

---
https://github.com/openyurtio/raven-controller-manager/blob/9473651096e284ca91c589a630dc0ab8616aabd3/charts/raven-controller-manager/templates/service.yaml#L27

```raven-controller-manager.labels``` is used for Deployment but not Pods. We should use ```selectorLabels``` here.
<br/>
The other Service ```raven-controller-manager-metrics-service``` can't match any endpoint too. I'm not sure about the usage of this service. If it is used for Prometheus metrics, the targetPort port is ```8080``` but not ```https``` according to
```
func main() {
	var metricsAddr string
	var enableLeaderElection bool
	var probeAddr string
	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metric endpoint binds to.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")

```
and in Deployment, no port is declared as ```https```. So I can't give any suggestion to this service, unless get more info about it's usage. 
Waiting for tips.

**Comment by njucjc** [comment]
this repo is migrated to [yurt-manager](https://github.com/openyurtio/openyurt/tree/master/cmd/yurt-manager), you can use yurt-manager's helm chart to install gateway manager.
